const express = require('express');
const { z } = require('zod');
const { pool, withTransaction } = require('../db');
const { requireRole } = require('../auth');
const { postJournal, reverseJournalEntry } = require('../services/ledger');
const { audit } = require('../services/audit');

const router = express.Router();

// GET /api/journal — list all entries (manual and auto-generated), newest first
router.get('/', async (req, res, next) => {
  try {
    const { rows: entries } = await pool.query(
      'select * from journal_entries where company_id=$1 order by date desc, created_at desc',
      [req.user.company_id]
    );
    const { rows: lines } = await pool.query(
      `select jl.*, a.name as account_name from journal_lines jl
       join accounts a on a.id = jl.account_id
       where jl.journal_entry_id = any($1::uuid[])`,
      [entries.map((e) => e.id)]
    );
    const byEntry = {};
    for (const l of lines) (byEntry[l.journal_entry_id] ||= []).push(l);
    res.json(entries.map((e) => ({ ...e, lines: byEntry[e.id] || [] })));
  } catch (err) { next(err); }
});

const lineSchema = z.object({
  accountId: z.string().uuid(),
  debit: z.number().min(0).default(0),
  credit: z.number().min(0).default(0),
});
const entrySchema = z.object({
  date: z.string(),
  memo: z.string().min(1),
  lines: z.array(lineSchema).min(2),
});

// POST /api/journal — post a manual journal entry. Only accountant+ may post directly;
// Sale/Purchase/Expense entries are posted internally by their own routes.
router.post('/', requireRole('accountant'), async (req, res, next) => {
  try {
    const body = entrySchema.parse(req.body);
    const entry = await withTransaction(async (client) => {
      const e = await postJournal(client, {
        companyId: req.user.company_id,
        date: body.date,
        memo: body.memo,
        source: 'Manual',
        lines: body.lines,
        createdBy: req.user.id,
      });
      if (e) await audit(client, { companyId: req.user.company_id, userId: req.user.id, action: 'create', entity: 'journal_entry', entityId: e.id, details: { memo: e.memo, date: e.date } });
      return e;
    });
    if (!entry) return res.status(400).json({ error: 'Entry has no non-zero lines.' });
    res.status(201).json(entry);
  } catch (err) {
    if (err.status) return res.status(err.status).json({ error: err.message });
    next(err);
  }
});

// PUT /api/journal/:id — edit a manual entry (only 'Manual' source entries; entries
// auto-generated by Sales/Purchases/Expenses must be edited via those modules so
// stock and party balances stay in sync).
router.put('/:id', requireRole('accountant'), async (req, res, next) => {
  try {
    const body = entrySchema.parse(req.body);
    const existing = await pool.query('select * from journal_entries where id=$1 and company_id=$2', [req.params.id, req.user.company_id]);
    if (!existing.rows[0]) return res.status(404).json({ error: 'Not found' });
    if (existing.rows[0].source !== 'Manual') {
      return res.status(400).json({ error: `This entry was generated by the ${existing.rows[0].source} module — edit it there.` });
    }
    const entry = await withTransaction(async (client) => {
      await reverseJournalEntry(client, req.params.id);
      const e = await postJournal(client, {
        companyId: req.user.company_id,
        date: body.date,
        memo: body.memo,
        source: 'Manual',
        lines: body.lines,
        createdBy: req.user.id,
      });
      if (e) await audit(client, { companyId: req.user.company_id, userId: req.user.id, action: 'update', entity: 'journal_entry', entityId: e.id, details: { replaced: req.params.id, memo: e.memo, date: e.date } });
      return e;
    });
    res.json(entry);
  } catch (err) {
    if (err.status) return res.status(err.status).json({ error: err.message });
    next(err);
  }
});

// DELETE /api/journal/:id — same restriction: manual entries only.
router.delete('/:id', requireRole('accountant'), async (req, res, next) => {
  try {
    const existing = await pool.query('select source from journal_entries where id=$1 and company_id=$2', [req.params.id, req.user.company_id]);
    if (!existing.rows[0]) return res.status(404).json({ error: 'Not found' });
    if (existing.rows[0].source !== 'Manual') {
      return res.status(400).json({ error: `This entry was generated by the ${existing.rows[0].source} module — delete it there.` });
    }
    await withTransaction(async (client) => {
      await reverseJournalEntry(client, req.params.id);
      await audit(client, { companyId: req.user.company_id, userId: req.user.id, action: 'delete', entity: 'journal_entry', entityId: req.params.id, details: { source: existing.rows[0].source } });
    });
    res.status(204).end();
  } catch (err) { next(err); }
});

module.exports = router;
